version: '3.6'

services:
  db:
    restart: always
    container_name: jee_database
    build: ./postgres
    env_file:
      - postgres/database.env
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
        read_only: false
    networks:
      - jee_network

  backend:
    restart: always
    container_name: jee_backend
    build: ./backend
    command: gunicorn dashboard.wsgi --bind 0.0.0.0:8000
    networks:
      - jee_network

  frontend:
    container_name: jee_frontend
    build: ./frontend
    volumes:
      - build_folder:/frontend/build
    networks:
      - jee_network

  webserver:
    container_name: jee_webserver
    build: ./webserver
    ports:
      - '8081:3000'
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - jee_network

volumes:
  database:
  build_folder:

networks:
  jee_network:
