i18n:
  languageCode: 'en-us'
  timezone: 'Asia/Kolkata'
secrets:
  secretKey: 'k!ujc!)sk4hmf07zz4wa399+nbwii9s9vr7w4(4v&+0$9qe0x1'
services:
  database:
    host: 'db'
    name: 'jee'
    user: 'jee_user'
    password: 'jee_password'
    port: 5432
